about/urls.py
from django.urls import path
from .views import Home
app_name = 'about'
urlpatterns = [
    path('', Home.as_view(), name='tes'),
    path('<str:input_string>/', Home.as_view(), name='Home'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Dashboard
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',Dashboard.as_view(template_name = 'index.html'),name='land'),
    path('tes/', include('about.urls', namespace='about')),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

about/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.




class Home(TemplateView):
    template_name = "about/index.html"

    def get_context_data(self, **kwargs):
        input_string = self.kwargs.get('input_string') 
        context = super().get_context_data(**kwargs)
        if input_string in kwargs:
            context.update({
            'judul':'about',
            'mydata': 'data',
            'input_string': input_string,
        })
        else:
            context.update({
            'judul':'about',
            'mydata': 'data',
            
        })
        return context

blog/views.py
from django.views.generic import TemplateView

class Dashboard(TemplateView):
    pass

about/templates/about/index.html
{% extends "base.html" %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include "snippets/styles.html" %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sacramento&family=Work+Sans:ital,wght@0,100;0,400;0,700;1,600&display=swap" rel="stylesheet">
    
    <title>My brother wedding</title>
</head>
<body>
    
    {% include "snippets/navbar.html" %} 
    {% include "snippets/home.html" %} 
    {% include "snippets/info.html" %}
    {% include "snippets/story.html" %}
    {% include "snippets/gallery.html" %}
    {% include "snippets/rsvp.html" %}
    {% include "snippets/gifts.html" %}
    {% include "snippets/footer.html" %}

     
    

    {% include "snippets/js.html" %}
    <script src="https://cdn.jsdelivr.net/npm/bs5-lightbox@1.8.3/dist/index.bundle.min.js"></script>
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include "snippets/styles.html" %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sacramento&family=Work+Sans:ital,wght@0,100;0,400;0,700;1,600&display=swap" rel="stylesheet">
    
    <title>My brother wedding</title>
</head>
<body>
  <section id="hero" class="hero w-100 h-100 p-3 mx-auto text-center d-flex justify-content-center align-items-center text-white">
      <main>
          <h4>Kepada<span> ,</span></h4>
          <h1> Ade chandra & Khairina</h1>
          <p>Aakan melangsungkan resepsi pernikahan dalam:</p>
          <div class="simply-countdown">

          </div>
          <a href="{% url 'about:tes'  %}" class="btn btn-lg mt-4" >lihat undangan</a>
      </main>
  </section>
  {% include "snippets/js.html" %}
</body>
</html>

templates/snippets/footer.html
<footer>
    <div class="container">
      <div class="row">
        <div class="col text-center">
          <small class="block">&copy; 2024 Ade chandra & Khairina wedding All Rights Reserved</small>
          <small class="block">Design by <a href="https://instagram.com/roni_efendi45">@roni_efendi45</a></small>
            <ul class="mt-3">
              <li>
                <a href=""><i class="bi bi-instagram"></i></a>
              </li>
              <li>
                <a href=""><i class="bi bi-facebook"></i></a>
              </li>
              <li>
                <a href=""><i class="bi bi-tiktok"></i></a>
              </li>
              <li>
                <a href=""><i class="bi bi-youtube"></i></a>
              </li>
            </ul>
        </div>
      </div>
    </div>
  </footer>

templates/snippets/gallery.html
<section id="gallery" class="gallery">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8 col-10 text-center">
          <span>Memori kisah kami</span>
          <h2>Galleri foto</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente unde, rem, et delectus neque soluta asperiores earum 
            doloribus excepturi ut quae obcaecati incidunt provident ipsum deserunt voluptas aperiam placeat voluptatibus.</p>
        </div>
      </div>

      <div class="row row-cols-lg-4 row-cols-md-3 row-cols-sm-2 row-cols-1 justify-content-center">
        <div class="col mt-3">
          <a href="https://picsum.photos/id/201/1200/768" data-toggle="lightbox" data-caption="1" data-gallery="mygallery">
            <img src="https://picsum.photos/id/101/400/400" alt="1" class="img-fluid w-100 rounded">
          </a>
        </div>
        <div class="col mt-3">
          <a href="https://picsum.photos/id/101/1200/768" data-toggle="lightbox" data-caption="2" data-gallery="mygallery" >
            <img src="https://picsum.photos/id/101/400/400" alt="2" class="img-fluid w-100 rounded">
          </a>
        </div>
        <div class="col mt-3">
          <a href="https://picsum.photos/id/102/1200/768" data-toggle="lightbox" data-caption="3" data-gallery="mygallery">
            <img src="https://picsum.photos/id/102/400/400" alt="3" class="img-fluid w-100 rounded">
          </a>
        </div>
        <div class="col mt-3">
          <a href="https://picsum.photos/id/103/1200/768" data-toggle="lightbox" data-caption="4" data-gallery="mygallery">
            <img src="https://picsum.photos/id/103/400/400" alt="4" class="img-fluid w-100 rounded">
          </a>
        </div>
        <div class="col mt-3">
          <a href="https://picsum.photos/id/104/1200/768" data-toggle="lightbox" data-caption="5" data-gallery="mygallery">
            <img src="https://picsum.photos/id/104/400/400" alt="5" class="img-fluid w-100 rounded">
          </a>
        </div>
        <div class="col mt-3">
          <a href="https://picsum.photos/id/106/1200/768" data-toggle="lightbox" data-caption="6" data-gallery="mygallery">
            <img src="https://picsum.photos/id/106/400/400" alt="6" class="img-fluid w-100 rounded">
          </a>
        </div>
      </div>
    </div>
  </section>

templates/snippets/gifts.html
{% load static %}
<div class="gifts" id="gifts">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8 col-10 text-center">
         <span>Ungkapan tanda kasih</span>
          <h2>Kirim hadiah</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque, eaque quod! Officia dicta voluptates nostrum iure ratione, 
            error ipsam a explicabo inventore, consequuntur, quisquam eos sed labore iste laboriosam! Dolor.</p>
        </div>
      </div>

      <div class="row justify-content-center text-center">
        <div class="col-md-6">
          <ul class="list-group">
            <li class="list-group-item">
              <div class="d-block fw-bold">BSI</div>
              1234556789-Ade chadra
            </li>
            <li class="list-group-item">
              <div class="fw-bold">Saweria</div>
              <img src="{% static 'img/saweria.png' %}" alt="saweria qr" class="img-thumbnail " width="150">
            </li>
          </ul>
        </div>
      </div>
      </div>
  </div>

templates/snippets/home.html
{% load static %}
<section id="home" class="home">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8 text-center">
          <h2>Acara pernikahan</h2>
          <h3>Diselenggarakan pada 20 November 2024 di Bukittinggi,Sumatera Barat. </h3>
          <p>oleh kareana itu dengan segala hormat,kami bermaksud mengundang Saudara/i, untuk hadir pada acara pernikahan kami</p>
        </div>

        <div class="row couple ">
          <div class="col-lg-6">
            <div class="row">
              <div class="col-8 text-end">
                <h3>Roni Efendi,S.T.</h3>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. 
                  Consequuntur impedit facere vitae nemo magni dolor!</p>
                <p>Putra dari bapak Nurfizal <br> dan <br> Ibu Kartini</p>
              </div>
              <div class="col-4">
                <img src="{% static 'img/Ade.png' %}" alt="" class="img-responsive rounded-circle">
              </div>
            </div>
          </div>

          <span class="heart"><img src="{% static 'img/heart-fill.svg' %}" alt=""></i></span>

          <div class="col-lg-6">
            <div class="row">
              <div class="col-4">
                <img src="{% static 'img/Ade.png' %}" alt="" class="img-responsive rounded-circle">
              </div>
              <div class="col-8 text-start">
                <h3>Roni Efendi,S.T.</h3>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. 
                  Consequuntur impedit facere vitae nemo magni dolor!</p>
                <p>Putra dari bapak Nurfizal <br> dan <br> Ibu Kartini</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/snippets/info.html
<section class="info" id="info">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8 col-10 text-center">
           <h2>Informasi Acara</h2>
           <p class="alamat">Alamat:Jl.Pemuda Gurun Tigo Kota Bukittinggi</p>
           <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.7637856665774!2d100.36749627404022!3d-0.29956973534171966!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2fd538a222080553%3A0x16cc6201690259a3!2sRumah%20Potong%20Hewan%20Bukittinggi!5e0!3m2!1sid!2sid!4v1706604843413!5m2!1sid!2sid" 
           width="100%" height="250" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
           <a href="https://maps.app.goo.gl/zff9VFDqDV3vQntn6" target="_blank" class="btn btn-light btn-sm my-3">Buka peta</a>
           <p class="description">Diharapkan untuk tidak salah alamat dan tanggal,manakala tiba di tujuan namun tidak ada tanda-tanda sedang
            dilangsungkan pernikahan,boleh jadi anda salah jadwal atau salah tempat.
           </p>
        </div>
      </div>

      <div class="row justify-content-center mt-4">
        <div class="col-md-5 col-10">
          <div class="card text-center text-bg-light mb-5">
            <div class="card-header">
              Akad Nikah
            </div>
            <div class="card-body">
              <div class="row justify-content-center ">
                <div class="col-md-6 ">
                  <i class="bi bi-calendar3 d-block"></i>
                  <span>08:00 - 10:00</span>
                </div>
                <div class="col-md-6">
                  <i class="bi bi-calendar3 d-block"></i>
                  <span>Minggu 20 November 2024</span>
                </div>
              </div>
            </div>
            <div class="card-footer ">
              Saat acara akad di harapkan untuk kondusif menjaga kekhidmatan dan kekhusuyuan seluruh prosesi.
            </div>
          </div>
        </div>
        <div class="col-md-5 col-10">
          <div class="card text-center text-bg-light">
            <div class="card-header">
              Resepsi
            </div>
            <div class="card-body">
              <div class="row justify-content-center ">
                <div class="col-md-6 ">
                  <i class="bi bi-calendar3 d-block"></i>
                  <span>11:00 - Selesai</span>
                </div>
                <div class="col-md-6">
                  <i class="bi bi-calendar3 d-block"></i>
                  <span>Minggu 20 November 2024</span>
                </div>
              </div>
            </div>
            <div class="card-footer ">
              Saat acara akad di harapkan untuk kondusif menjaga kekhidmatan dan kekhusuyuan seluruh prosesi.
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/snippets/js.html
{% load static %}
<script src="{% static 'vendor/bootstrap/js/bootstrap.js' %}"></script>
<script src="{% static 'js/simplyCountdown.min.js' %}"></script>
<script src="{% static 'js/countdown.js' %}"></script>

templates/snippets/navbar.html
<nav class="navbar navbar-expand-md bg-transparent sticky-top mynavbar">
    <div class="container">
      <a class="navbar-brand" href="#">Ade chandra & Khairina</a>
      <button class="navbar-toggler border-0 " type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Ade chandra & Khairina</h5>
          <button type="button" class="btn-close " data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <div class="navbar-nav ms-auto">
            <a class="nav-link"  href="#home">Home</a>
            <a class="nav-link" href="#info">Info</a>
            <a class="nav-link" href="#story">Story</a>
            <a class="nav-link" href="#gallery">Galery</a>
            <a class="nav-link" href="#rsvp">RSVP</a>
            <a class="nav-link" href="#gifts">Gifts</a>
          </div>
        </div>
      </div>
    </div>
  </nav>

templates/snippets/rsvp.html
<section id="rsvp" class="rsvp">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8 col-10 text-center">
         <h2>Konfirmasi kehadiran</h2>
          <p>Isi form di bawah ini untuk melakukan konfirmasi kehadiran</p>
        </div>
      </div>
      <form class="row row-cols-md-auto g-3 align-items-center justify-content-center" method="POST"
          action="https://script.google.com/macros/s/AKfycbyddFbEeA6OmZAuNf0jw_B30ZUOS5qSDwlAKV_nurcW7H6osJx2ZWnIeTmPm_35g/exec" id="my-form">
        <div class="col-12">
          <div class="mb-3">
            <label for="nama" class="form-label">Nama</label>
            <input type="text" class="form-control" id="nama"  name="nama">
          </div>
        </div>
        <div class="col-12">
          <div class="mb-3">
            <label for="jumlah" class="form-label">jumlah</label>
            <input type="number" class="form-control" id="jumlah"  name="jumlah" min="1" max="5" length="1" value="1">
          </div>
        </div>
        <div class="col-12">
          <div class="mb-3">
            <label for="status" class="form-label">Konfirmasi</label>
            <select name="status" id="status" class="form-select">
              <option selected>Pilih salah satu</option>
              <option value="1">Hadir</option>
              <option value="0">Tidak hadir</option>
            </select>
          </div>
        </div>
        <div class="col-12 kirim" style="margin-top:35px;">
          <button class="btn btn-primary">Kirim</button>
        </div>
        </form>
        <div class="row justify-content-center mt-5">
          <div class="col-md-6">
            <div id="disqus_thread"></div>

  </section>

templates/snippets/story.html
<section id="story" class="story">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8 col-10 text-center">
          <span>Bagaiamana cinta kami bersemi</span>
          <h2>Cerita kami</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente unde, rem, et delectus neque soluta asperiores earum 
            doloribus excepturi ut quae obcaecati incidunt provident ipsum deserunt voluptas aperiam placeat voluptatibus.</p>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <ul class="timeline">
            <li>
                <div class="timeline-image" style="background-image: url(https://picsum.photos/299/300);">

              </div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                    <h3>Pertama Bertemu</h3>
                    <span>1 Juli 2014</span>
                </div>
                <div class="timeline-body">
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
                    Quis dolores sequi facilis perspiciatis, aliquid corporis?</p>
                </div>
              </div>
            </li>

            <li class="timeline-inverted">
              <div class="timeline-image" style="background-image: url(https://picsum.photos/300/300);">

              </div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                    <h3>Mulai serius</h3>
                    <span>1 Juli 2014</span>
                </div>
                <div class="timeline-body">
                  <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
                    Neque labore iste sed, hic quos illum delectus ex adipisci!</p>
                </div>
              </div>
            </li>
            <li>
              <div class="timeline-image" style="background-image: url(https://picsum.photos/301/300);">

              </div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                    <h3>Tunangan</h3>
                    <span>1 Juli 2014</span>
                </div>
                <div class="timeline-body">
                  <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
                    Neque labore iste sed, hic quos illum delectus ex adipisci!</p>
                </div>
              </div>
            </li>
            
          </ul>
        </div>
      </div>
    </div>
  </section>

templates/snippets/styles.html
{% load static  %}
<link rel="stylesheet" href="{%  static 'vendor/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{%  static 'css/styles.css' %}">
<link rel="stylesheet" href="{%  static 'css/simplyCountdown.theme.default.css' %}">